export default [
    {
        title: "Bagel and cream cheese",
        id: "1",
        desc: "How we dream about our future",
        price: "$6.99",
        category: "breakfast",
        thumbnail: "https://i.ibb.co/C2VxmLM/breakfast4.png",
    },
    {
        title: "Breakfast sandwich",
        id: "2",
        desc: "How we dream about our future",
        price: "$9.99",
        category: "breakfast",
        thumbnail: "https://i.ibb.co/TkdXC5s/breakfast2.png",
    },
    {
        title: "Baked Chicken",
        id: "3",
        desc: "How we dream about our future",
        price: "$10.99",
        category: "breakfast",
        thumbnail: "https://i.ibb.co/RvvDBgF/breakfast3.png",
    },
    {
        title: "Eggs Benedict",
        id: "4",
        desc: "How we dream about our future",
        price: "$8.99",
        category: "breakfast",
        thumbnail: "https://i.ibb.co/y0yZ3Yv/breakfast1.png",
    },
    {
        title: "Toast Croissant Fried egg",
        id: "5",
        desc: "How we dream about our future",
        price: "$19.99",
        category: "breakfast",
        thumbnail: "https://i.ibb.co/1Lzh3qN/breakfast6.png",
    },
    {
        title: "Full Breakfast Fried Egg Toast Brunch",
        id: "6",
        desc: "How we dream about our future",
        price: "$3.99",
        category: "breakfast",
        thumbnail: "https://i.ibb.co/8cM8bcT/breakfast5.png",
    },
    {
        title: "Healthy Meal Plan",
        id: "7",
        desc: "How we dream about our future",
        price: "$23.99",
        category: "lunch",
        thumbnail: "https://i.ibb.co/yyMNSZv/lunch6.png",
    },

    {
        title: "Fried Chicken Bento",
        id: "8",
        desc: "How we dream about our future",
        price: "$9.99",
        category: "lunch",
        thumbnail: "https://i.ibb.co/S3xf4y4/lunch5.png",
    },
    {
        title: "Tarragon-Rubbed-Salmon",
        id: "9",
        desc: "How we dream about our future",
        price: "$6.99",
        category: "lunch",
        thumbnail: "https://i.ibb.co/GvYsDjz/lunch3.png",
    },
    {
        title: "Indian Lunch",
        id: "10",
        desc: "How we dream about our future",
        price: "$8.99",
        category: "lunch",
        thumbnail: "https://i.ibb.co/V2g6P9y/lunch4.png",
    },
    {
        title: "Beef Steak",
        id: "11",
        desc: "How we dream about our future",
        price: "$15.99",
        category: "lunch",
        thumbnail: "https://i.ibb.co/qrvQqps/lunch1.png",
    },
    {
        title: "Honey-Soy-Glazed Salmom with Peppers",
        id: "12",
        desc: "How we dream about our future",
        price: "$7.99",
        category: "lunch",
        thumbnail: "https://i.ibb.co/5sf7cHT/lunch2.png",
    },
    {
        title: "Salmon with Grapefruit and Lentil Salad",
        id: "13",
        desc: "How we dream about our future",
        price: "$9.99",
        category: "dinner",
        thumbnail: "https://i.ibb.co/hMbcCMH/dinner6.png",
    },
    {
        title: "Lemony Salmon Piccata",
        id: "14",
        desc: "How we dream about our future",
        price: "$10.99",
        category: "dinner",
        thumbnail: "https://i.ibb.co/YXcvCqw/dinner2.png",
    },
    {
        title: "Chicken Tenderloin Without Bone",
        id: "15",
        desc: "How we dream about our future",
        price: "$12.99",
        category: "dinner",
        thumbnail: "https://i.ibb.co/p0gP6c1/dinner5.png",
    },
    {
        title: "French fries with cheese",
        id: "16",
        desc: "How we dream about our future",
        price: "$8.99",
        category: "dinner",
        thumbnail: "https://i.ibb.co/FnFC6m3/dinner4.png",
    },
    {
        title: "Garlic Butter Baked Salmon",
        id: "17",
        desc: "How we dream about our future",
        price: "$6.99",
        category: "dinner",
        thumbnail: "https://i.ibb.co/Jp5V0yC/dinner3.png",
    },
    {
        title: "Baked Chicken",
        id: "18",
        desc: "How we dream about our future",
        price: "$9.99",
        category: "dinner",
        thumbnail: "https://i.ibb.co/hX6xjQb/dinner1.png",
    },
];